# Generated by Django 5.0.7 on 2024-07-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productBrand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productInfo',
            new_name='iInfo',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productPrice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
