# Generated by Django 5.0.7 on 2024-07-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_productbrand_products_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productName',
            new_name='name',
        ),
    ]
