# Generated by Django 5.0.7 on 2024-07-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_rename_productname_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='iInfo',
            new_name='info',
        ),
    ]
