# Generated by Django 5.0.7 on 2024-07-30 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_rename_stockcount_products_stockcount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Sales',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='valor',
            new_name='value',
        ),
    ]
