# Generated by Django 5.0.7 on 2024-07-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_products_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='qty',
        ),
    ]
