# Generated by Django 5.0.7 on 2024-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
