# Generated by Django 5.0.7 on 2024-08-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
